# Generated by Django 6.0.2 on 2026-04-01 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('skills', '0003_learningprogress_saved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='target_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skills.jobrole'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='career_goal',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
