# Generated by Django 6.0.2 on 2026-03-28 10:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_learningprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learningprogress',
            name='saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='learningprogress',
            unique_together={('user', 'resource')},
        ),
    ]
